name: hotel_reservation_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  flutter_stripe: ^10.1.1
  app_state: ^0.9.6

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.9.1

  model_viewer_plus: ^1.7.0
  panorama_viewer: 2.0.7    # ⭐ 改成 panorama_viewer，替代 panorama 插件
  star_rating: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rooms/
    - assets/icons/hotel_icon.png
    - assets/seacity.jpg
    - assets/models/

    # ✅ 新增：把整个 videos 文件夹加入（不影响你下面已写的两个 mp4）
    - assets/videos/

    - assets/videos/splash.mp4
    - assets/services/     # ⭐ pool.jpg、pool_360.jpg、gym.jpg、gym_360.jpg 等
    - assets/gifs/final2.gif
    - assets/gifs/final3.gif
    - assets/gifs/final4.gif
    - assets/gifs/final5.gif
    - assets/videos/booking_success.mp4
