// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqhpVGcTyzXmKPjradzg_1xuDKTOb5MM',
    appId: '1:486359900752:web:76dde6c80f25c0071e2755',
    messagingSenderId: '486359900752',
    projectId: 'hotel-reservation-app-e9d43',
    authDomain: 'hotel-reservation-app-e9d43.firebaseapp.com',
    storageBucket: 'hotel-reservation-app-e9d43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiN5R5ieG9QxrbkL8FujW8u3EGRgpLAYA',
    appId: '1:486359900752:android:10c6ef39b79671771e2755',
    messagingSenderId: '486359900752',
    projectId: 'hotel-reservation-app-e9d43',
    storageBucket: 'hotel-reservation-app-e9d43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLvTxwwkPLnBj66DYDjp57T-dxg3_lFY',
    appId: '1:486359900752:ios:3b8952d0e9be2db51e2755',
    messagingSenderId: '486359900752',
    projectId: 'hotel-reservation-app-e9d43',
    storageBucket: 'hotel-reservation-app-e9d43.firebasestorage.app',
    iosBundleId: 'com.example.hotelReservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLvTxwwkPLnBj66DYDjp57T-dxg3_lFY',
    appId: '1:486359900752:ios:3b8952d0e9be2db51e2755',
    messagingSenderId: '486359900752',
    projectId: 'hotel-reservation-app-e9d43',
    storageBucket: 'hotel-reservation-app-e9d43.firebasestorage.app',
    iosBundleId: 'com.example.hotelReservationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgqhpVGcTyzXmKPjradzg_1xuDKTOb5MM',
    appId: '1:486359900752:web:f3bb9d1fe4c7e87b1e2755',
    messagingSenderId: '486359900752',
    projectId: 'hotel-reservation-app-e9d43',
    authDomain: 'hotel-reservation-app-e9d43.firebaseapp.com',
    storageBucket: 'hotel-reservation-app-e9d43.firebasestorage.app',
  );
}
